# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-22 20:16
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 22, 20, 16, 52, 643959, tzinfo=utc)),
        ),
    ]
